query GetTeams {
  getTeams {
    teams {
      id
      name
      isOwner
      channels {
        id
        name
        events {
          ...FEvent
        }
      }
    }
    errors {
      ...FError
    }
  }
}
